### ISSUE TITLE
Create Reminders

### ISSUE THREAD

**Issue by CKone2k** [CKone2k/CK-capstone#2]
## Value proposition

As a User
I want to create personal goals and set reminders  
in order to have a personal experience.

## Description
<img width="288" alt="Screenshot 2023-04-26 at 10 08 05" src="https://user-images.githubusercontent.com/125925578/234514777-aaac5dba-a9e2-41ff-817b-3476d90cfcce.png">

## Acceptance criteria

- [ ] We can give our goal a name
- [ ] We need to be able to describe how we achieve our goal in order to have an easy reminder
- [ ] add more descriptions if needed and also delete descriptions we don't need
- [ ] A dropdown selector for easy organization of our goals
- [ ] The option to post the goal publicly or in private 
## Tasks

- [ ] create Text field for the title of the goal
- [ ] create text area for description text
- [ ] button to add more text areas
- [ ] create toggle button to switch from public post to private
- [ ] create a dropdown selector for categories
 

Size: L

**Comment by onemanwenttomow** [comment]
I have some questions. 
* Is this a page by itself? Or is it a modal on another page? 
* If it is a separate page, will the user be redirected back to the "main" page?
* Will it be it's own component? If so i would add the creation of said component (including name) to the tasks. 
* What does clicking on the `add activity` button do? 
* How do you plan to implement the privacy toggle button? Will it be a checkbox or a radio group or something else?
* What is the `Category selection`? Is this a drop down menu with pre-filled items? Or something else? I am not sure what the following means? 

> to set with different time settings

* Can a user select more than one category in the `Category selection`?

**Comment by onemanwenttomow** [comment]
I am still not sure what clicking on the add activity button does? Maybe you can clarify that?
