### ISSUE TITLE
reminder display

### ISSUE THREAD

**Issue by CKone2k** [CKone2k/CK-capstone#6]
## Value proposition

As a user
I want to have a notification on my phone
in order to get reminded of the set activities

## Description

<img width="429" alt="Screenshot 2023-04-24 at 15 44 01" src="https://user-images.githubusercontent.com/125925578/234014938-92ee68cb-798d-47fd-89cd-daffec6ab0df.png">

## Acceptance criteria

- [ ]  must show the selcted reminders in the time frame
- [ ] display the selcted reminders activitys

## Tasks

- [ ] display activity imported from main page
- [ ] display activity description

Size:
